django/slides/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views 

app_name = 'slides'
urlpatterns = [
    url(r'^upload/(?P<course>[a-zA-Z0-9_]+)/(?P<token>[a-zA-Z0-9_]+)', views.upload),
    url(r'^api/register/$', views.register),
    url(r'^api/login/$', views.login),
    url(r'^api/logout/$', views.logout),
    
    url(r'^clicker_next/', views.clicker_next),
    url(r'^clicker_prev/', views.clicker_prev),
    url(r'^clicker_menu/', views.clicker_menu),
    url(r'^clicker_full/', views.clicker_full),

    url(r'^getpdf/', views.pdf_view),
    url(r'^returnsomejson/', views.returnsomejson),
#    url(r'^profile/', views.index),
    url(r'^login/', views.login),
    url(r'^logout/$', views.logout_view, name='logout'),
#    url(r'^$', views.index, name='index'),
    url(r'^course_list/', views.course_list, name='course list'),
    url(r'^select_lecture/([a-zA-Z0-9_]+)', views.select_lecture, name='select lecture'),
    url(r'^lecture_list/([a-zA-Z0-9_]+)', views.lecture_list, name='lecture list'),
    url(r'^get_pdf/', views.get_pdf, name='get pdf'),
    url(r'^lecture/get_page_questions/', views.get_page_questions, name='get page questions'),
    url(r'^lecture/get_qform/', views.get_qform, name='get qform'),
    url(r'^lecture/get_curr_page/', views.get_curr_page, name='get curr page'),
    url(r'^lecture/get_mood/', views.get_mood, name='get mood'),
    url(r'^lecture/get_speed/', views.get_speed, name='get speed'),
    url(r'^lecture/check_speed/', views.check_speed, name='check speed'),
    url(r'^lecture/go_next_page/', views.go_next_page, name='go next page'),
    url(r'^lecture/go_prev_page/', views.go_prev_page, name='go previous page'),
    url(r'^lecture/go_curr_page/', views.go_curr_page, name='go current page'),
    url(r'^lecture/vote_up/', views.vote_up, name='vote up'),
    url(r'^lecture/vote_down/', views.vote_down, name='vote down'),
    url(r'^lecture/too_slow/', views.too_slow, name='too slow'),
    url(r'^lecture/too_fast/', views.too_fast, name='too fast'),
    url(r'^lecture/question/', views.question, name='question'),
    url(r'^lecture/qvote/([a-zA-Z0-9_]+)', views.qvote, name='qvote'),
    url(r'^lecture/show_questions/', views.show_questions, name='show questions'),
    url(r'^trigger_anything/', views.trigger_anything, name='trigger anything'),
    #lecture/ must be at the bottom otherwise it will always be matched first
#    url(r'^lecture/', views.lecture, name='lecture'),
]

django/slides_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^slides/', include('slides.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('slides.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/slides/models.py
import json
from django.db import models
from django.contrib.auth.models import User, Group
from channels import Group as Channel_Group
from django.shortcuts import get_object_or_404
import os
from django.forms import ModelForm
from django import forms
import binascii

# Create your models here.

class Token(models.Model):
    user = models.ForeignKey(User)
    token = models.CharField(max_length=40, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = self.generate_token()
        return super(Token, self).save(*args, **kwargs)

    def generate_token(self):
        return binascii.hexlify(os.urandom(20)).decode()

    def __unicode__(self):
        return self.token


###############

def rename(instance, filename):
    return '/'.join([filename])

class PDF(models.Model):
    filename = models.CharField(max_length=200)
    course = models.ForeignKey(Group, on_delete=models.CASCADE, default = 1)
    lecturer = models.ForeignKey(User, on_delete=models.CASCADE, default = 1)
    current_page = models.IntegerField(default = 1)
    pdffile = models.FileField(upload_to=rename)

    def __str__(self):
        return self.filename

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = PDF.objects.get(id=self.id)
            if this.pdffile != self.pdffile:
                this.pdffile.delete(save=False)
        except: pass           
        super(PDF, self).save(*args, **kwargs)

class PDFForm(ModelForm):
    class Meta:
        model = PDF
        fields = ['pdffile', 'filename']


class Current(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default = 1)
    pdf = models.ForeignKey(PDF, on_delete=models.CASCADE, default = 1) 
    page = models.IntegerField()
    active = models.IntegerField(default = 0)

    def __str__(self):
        return str(self.owner) +' '+ str(self.pdf) +' page'+ str(self.page)  + (' active' if (self.active == 1) else ' inactive')

class Votes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf = models.ForeignKey(PDF, on_delete=models.CASCADE)
    page = models.IntegerField()
    value = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user) +' '+ str(self.pdf) +' page'+ str(self.page)  + (' happy' if (self.value == 0) else ' unhappy')

class Speed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf = models.ForeignKey(PDF, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user) +' '+ str(self.pdf) + (' slow' if (self.value == 0) else ' fast')

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf = models.ForeignKey(PDF, on_delete=models.CASCADE)
    page = models.IntegerField()
    text = models.TextField(verbose_name = 'Question')

    def __str__(self):
        return str(self.user) +' '+ str(self.pdf) +' page'+ str(self.page)+' '  + self.text

class Question_Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) +' likes '+ str(self.question)

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text']

django/slides/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse;
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from .models import Current, PDF, Votes, PDFForm, Question, QuestionForm, Question_Vote, Speed
from django.contrib.auth.models import User, Group
from channels import Group as Channel_Group
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.db.models import Count
#from .forms import PDFForm
import os
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder


from .utils import json_response, token_required
from django.views.decorators.csrf import csrf_exempt
from django.db import IntegrityError
from .models import Token

# Create your views here.
@csrf_exempt
@token_required
def clicker_full(request):
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    pdf = current.pdf
    notification = {
        "type": 'clicker',
        "nav": 'full',
    }
    Channel_Group(str(pdf.pk)).send({
       "text": json.dumps(notification),
    })
    return JsonResponse({'ack':False})

@csrf_exempt
@token_required
def clicker_next(request):
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    pdf = current.pdf
    notification = {
        "type": 'clicker',
        "nav": 'next',
    }
    Channel_Group(str(pdf.pk)).send({
       "text": json.dumps(notification),
    })
    return JsonResponse({'ack':False})

@csrf_exempt
@token_required
def clicker_prev(request):
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    pdf = current.pdf
    notification = {
        "type": 'clicker',
        "nav": 'prev',
    }
    Channel_Group(str(pdf.pk)).send({
       "text": json.dumps(notification),
    })
    return JsonResponse({'ack':False})

@csrf_exempt
@token_required
def clicker_menu(request):
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    pdf = current.pdf
    notification = {
        "type": 'clicker',
        "nav": 'menu',
    }
    Channel_Group(str(pdf.pk)).send({
       "text": json.dumps(notification),
    })
    return JsonResponse({'ack':False})



def pdf_view(request):
    print (os.path.join(settings.MEDIA_ROOT, 'Backpropagation.pdf'))
    with open(os.path.join(settings.MEDIA_ROOT,'slides.pdf') ,'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        response['Access-Control-Allow-Headers'] = 'Range'
        response['Access-Control-Expose-Headers'] = 'Accept-Ranges, Content-Encoding, Content-Length, Content-Range'
        return response
    pdf.closed


@csrf_exempt
@token_required
def returnsomejson(request):
  #Votes.send_notif()
  return json_response({'x':'something'})

'''
@csrf_exempt
@token_required
def course_index(request, course):
    course_group = Group.objects.get(name = course)
    # Handle file upload
    if request.method == 'POST':
        form = PDFForm(request.POST, request.FILES)
        if form.is_valid():
            pdf = form.save(commit=False)
            pdf.course = course_group
            pdf.lecturer = request.token.user
            pdf.save()
            # Redirect to the document list after POST
            return HttpResponseRedirect(course)
    else:
        form = PDFForm()  # A empty, unbound form

    # Load documents for the list page
    documents = PDF.objects.filter(course = course_group)

    return render_to_response(
        'slides/course_index.html',
        {'documents': documents, 'form': form},
        context_instance=RequestContext(request)
    )

    # Render list page with the documents and the form
    if(request.token.user.groups.filter(name = 'Lecturer').count() == 1):
        return render(request, 'slides/course_index.html', {'course': course, 'lecturer':True, 'documents': documents, 'form': form})
    else:
        return render(request, 'slides/course_index.html', {'course': course, 'documents': documents, 'form': form})
'''

@csrf_exempt
def upload(request, course, token):
    token = Token.objects.get(token=token)
    course_group = Group.objects.get(name = course)
    # Handle file upload
    if request.method == 'POST':
        form = PDFForm(request.POST, request.FILES)
        if form.is_valid():
          pdf = form.save(commit=False)
          pdf.course = course_group
          pdf.lecturer = token.user
          pdf.save()
            # Redirect to the document list after POST
#          return JsonResponse({'ack':True})
          return HttpResponseRedirect('http://146.169.47.210:9000/#/mainmenu/')
        return JsonResponse({'ack':False})
    else:
        form = PDFForm()  # A empty, unbound form
        return JsonResponse({'ack':False})


@csrf_exempt
@token_required
def course_list(request):
# returns a list of courses the user is subscribed to
# access c in course, c.pk, c.fields.name
    user_courses = serializers.serialize("json", request.token.user.groups.exclude(name = 'Lecturer').exclude(name = 'Student'))
    return JsonResponse(user_courses, safe = False)

@csrf_exempt
@token_required
def lecture_list(request, course):
# returns a list of lectures(pdfs) in the selected course
# access doc in documents, doc.pk, doc.fields.filename, doc.fields.someotherfield
    course_group = Group.objects.get(pk = course)
    documents = serializers.serialize("json", PDF.objects.filter(course = course_group))
    return JsonResponse(documents, safe=False)


@csrf_exempt
@token_required
def select_lecture(request, key):
# selects PDF with the key and marks as the user's active
# returns true after selected
#deactive all other actives.
    try:
        other = Current.objects.get(owner = request.token.user, active=1)
        other.active = 0
        other.save()
    except Current.DoesNotExist:
        pass

    try:
        curr_pdf = get_object_or_404(PDF, pk = key)
        current = Current.objects.get(owner = request.token.user, pdf = curr_pdf)
        current.active = 1
        current.save()
    except Current.DoesNotExist:
        current = Current(owner = request.token.user, pdf = curr_pdf, page=1, active=1)
        current.save()

    return JsonResponse({'ack':True})

'''
@csrf_exempt
@token_required
def lecture(request):
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    pdf = current.pdf

    votes = get_votes(request);
    good = votes['good']
    bad = votes['bad']
    total = votes['total']

    if(request.token.user.groups.filter(name = 'Lecturer').count() == 1):
        return render(request, 'slides/lecture.html', {'pdffile': pdf.pdffile.url, 'pageCount':current.page, 'lecturer':True, 'votes_amplified':bad *100 / total, 'votes_rest': good*100/total})
    else:
        question_form = QuestionForm()
        curr_qs = Question.objects.filter(pdf = current.pdf, page = current.page)
        displayQ = curr_qs.annotate(votes = Count('question_vote')).order_by('-votes')
        return render(request, 'slides/lecture.html', {'pdffile': pdf.pdffile.url, 'pageCount':current.page, 'student':True, 'qform':question_form, 'questions': displayQ, 'votes_amplified':bad*100/total, 'votes_rest': good*100/ total})
'''

@csrf_exempt
@token_required
def get_pdf(request):
    current = get_object_or_404(Current, owner = request.token.user, active=1)
#    user = User.objects.get(username = 'lecturer1')
#    current = Current.objects.get(owner = user, active = 1)
#    print (os.path.join(settings.MEDIA_ROOT, current.pdf.pdffile))
    with open(os.path.join(settings.MEDIA_ROOT, str(current.pdf.pdffile)) ,'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename= current.pdf.filename '
        response['Access-Control-Allow-Headers'] = 'Range'
        response['Access-Control-Expose-Headers'] = 'Accept-Ranges, Content-Encoding, Content-Length, Content-Range'
        return response
    pdf.closed


@csrf_exempt
@token_required
def get_page_questions(request):
# returns list of questions on user's page on the pdf, can be used q.pk, q.fields.pk, q.fields.vote
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    curr_qs = Question.objects.filter(pdf = current.pdf, page = current.page)
    qs = curr_qs.annotate(votes = Count('question_vote')).order_by('-votes').values()
    displayQ = json.dumps(list(qs), cls=DjangoJSONEncoder)
    return JsonResponse(displayQ, safe=False)



@csrf_exempt
@token_required
def get_qform(request):
# returns a blank question form if the user can vote
# returns false otherwise
    if (current.pdf.current_page >= current.page):
        current = get_object_or_404(Current, owner = request.token.user, active=1)
        question_form = QuestionForm()
        return JsonResponse({'qform':question_form})
    else:
        return JsonResponse({'qform':False})


@csrf_exempt
@token_required
def get_curr_page(request):
# returns current page number for the user
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    return JsonResponse({'page':current.page})


@csrf_exempt
@token_required
def get_mood(request):
# return mood status as percentages
    current = get_object_or_404(Current, owner = request.token.user, active=1)
    curr_pdf = current.pdf

    canVote = curr_pdf.current_page >= current.page
    if(canVote and request.token.user.groups.filter(name = 'Student').count() == 1):
        try:
            myvote = Votes.objects.get(user = request.token.user, pdf = curr_pdf, page = current.page)
        except Votes.DoesNotExist:

django/slides/templates/slides/course_index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{course}}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'slides/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'slides/css/lumen.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'slides/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
</head>

<body id="page-top" class="index">
    <h1>{{course}}</h1>
    <div>
    <!-- List of uploaded documents -->
    {% if documents %}
        {% for document in documents %}
            <p> {{document.filename}} : 
                <a href="{{ document.pdffile.url }}">{{ document.pdffile.name }}</a>
            <a href="/slides/select/{{document.pk}}" class="btn btn-primary btn-lg">{{document.filename}}</a>
            </p>
        {% endfor %}
    {% else %}
        <p>No Lectures.</p>
    {% endif %}
    </div>

    <div>
    {% if lecturer %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'slides:course_index' course %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="Input">
            <p> Lecture: {{ form.filename }} </p>
            <p>{{ form.non_field_errors }}</p>

            <p>
                {{ form.pdffile.errors }}
                {{ form.pdffile }}
            </p>

            <input type="submit" class="btn btn-danger" value="Upload"/>
            </div>
        </form>
    {% endif %}
    </div>
   
    <a href="{% url 'slides:logout' %}" class="btn btn-danger">Logout</a>

    <!-- jQuery -->
    <script src="{% static 'slides/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'slides/js/bootstrap.min.js' %}"></script>

    <script>
        var lectureCount = 0; 
        
        function addLecture(parentId, childId) {
          var par = document.getElementById(parentId);
          var child = document.createElement('div');
          child.setAttribute('id', childId);
          child.innerHTML = 'Lecture Name: <input type="text" name="lectureInputs[]"/>\<p>{{ form.non_field_errors }}</p>\<p>{{ form.pdffile.label_tag }} {{ form.pdffile.help_text }}</p>\<p>{{ form.pdffile.errors }}\{{ form.pdffile }}\</p>\<input type="button" onclick="javascript:removeLecture(lectureCount)" class="btn btn-danger" value="Remove"/>\<input type="button" class="btn btn-danger" value="Add Lecture"/>';
          par.appendChild(child);
          child.download = "index.html";
        }

        function removeLecture(lectureNum) {
          document.getElementById('Lecture ' + lectureNum).parentNode.removeChild(elem);
        }

        function add() {
          lectureCount++;
          addLecture('Input', 'Lecture ' + lectureCount);
        }
    </script>
</body>

</html>

django/slides/templates/slides/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Courses</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'slides/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'slides/css/lumen.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'slides/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
</head>

<body id="page-top" class="index">
    <h1>Courses</h1>
    <div>
    <!-- List of user courses -->
    {% if courses %}
        {% for course in courses %}
	    <p>
            <a href="/slides/course_index/{{course}}" class="btn btn-primary btn-lg">{{course}}</a>
            </p>
        {% endfor %}
    {% else %}
        <p>User has not joined any courses.</p>
    {% endif %}
    </div>

 
    <a href="{% url 'slides:logout' %}" class="btn btn-danger">Logout</a>

    <!-- jQuery -->
    <script src="{% static 'slides/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'slides/js/bootstrap.min.js' %}"></script>

</body>

</html>

django/slides/templates/slides/lecture.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lecture</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'slides/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'slides/css/lumen.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'slides/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <script>
       socket = new WebSocket("ws://127.0.0.1:8000/all/");
       socket.onmessage = function(message){
         var data = JSON.parse(message.data);
         if(data.green_bar || data.red_bar){
           document.getElementById("red_bar").style.width = data.red_bar + '%';
           document.getElementById("green_bar").style.width = data.green_bar + '%';
         }
       }
    </script>

</head>

<body id="page-top" class="index">
    <h1>Slide</h1>
<!--
    <img src="{{ slide.img_source }}" width='70%'>

    <div id="sample" style="height:500px; width:700px"></div>
-->
    <canvas id="pdfviewer" style="border:1px solid black; height:500px; width:700px"></canvas>

    {% if lecturer %}
    <a href="{% url 'slides:previous page' %}" id="prev" class="btn btn-primary btn-lg">Previous</a>
    <a href="{% url 'slides:next page' %}" id="next" class="btn btn-primary btn-lg">Next</a>
    <li><a href="{% url 'slides:show questions' %}" class="btn btn-primary btn-lg">Questions</a></li>

    {% endif %}
    {% if student %}
    <a href="{% url 'slides:previous page' %}" class="btn btn-primary btn-lg">previous</a>
    <a href="{% url 'slides:next page' %}" id="student_next" class="btn btn-primary btn-lg">next</a>
    <a href="{% url 'slides:current page' %}" class="btn btn-primary btn-lg">current page</a>
    <br>
    <a href="{% url 'slides:vote up' %}" class="btn btn-success"><i class="fa fa-smile-o fa-3x" aria-hidden="true"></i></a>
    <a href="{% url 'slides:vote down' %}" class="btn btn-danger"><i class="fa fa-frown-o fa-3x" aria-hidden="true"></i></a>
    <br>
    <form action="{% url 'slides:question' %}" method="post">
    {% csrf_token %}
		{{ qform }}
		<input type="submit" value="Submit" />
    </form>
    <br>
	{% for q in questions %}
		<p> {{q.text}} : {{q.votes}} votes
		<a href="qvote/{{q.pk}}" class="btn btn-primary btn-lg">Vote</a>
		</p>
	{% endfor %}
    {% endif %}

    <h4>Current class status</h4>
    <div class="progress progress-striped active">
        <div id="red_bar" class="progress-bar progress-bar-danger" style="width: {{ votes_amplified }}%"></div>
        <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
        <div id="green_bar" class="progress-bar progress-bar-success" style="width: {{ votes_rest }}%"></div>
    </div>

    <a href="/slides/" class="btn btn-danger">Main Menu</a>
    <a href="{% url 'slides:logout' %}" class="btn btn-danger">Logout</a>

    <p id="demo"></p>

    <!-- jQuery -->
    <script src="{% static 'slides/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'slides/js/bootstrap.min.js' %}"></script>

<!--
    <script src="{% static 'slides/js/pdfobject.js' %}"></script>
    <script> PDFObject.embed("../../media/uploads/current.pdf", "#sample");</script>
-->
    <script src="{% static 'slides/js/pdf.js' %}"></script>


    <script>  
      var url ="/../..{{pdffile}}";
      var maxPages = 0;
      var scale = 1.5;
      var canvas = document.getElementById('pdfviewer');
      var context = canvas.getContext('2d');
      var viewport = 0;
      var renderContext = 0;
      getPDF();
      function getPDF() {
        PDFJS.workerSrc = "{% static 'slides/js/pdf.worker.js' %}";
        PDFJS.getDocument(url).then(function getPdfViewer(pdf) {
          // Fetch the first page
          maxPages = pdf.numPages;
          pdf.getPage({{pageCount}}).then(function getPageViewer(page) {
            viewport = page.getViewport(scale);
            // Prepare canvas using PDF page dimensions
            canvas.height = viewport.height;
            canvas.width = viewport.width;
            // Render PDF page into canvas context
            renderContext = {
              canvasContext: context,
              viewport: viewport
            };
           page.render(renderContext);
          });
          checkmax();
        });
      }
      
    </script>

    <script>
      function checkmax() {
        {% if lecturer %}
        if ({{pageCount}} >= maxPages) {
     
          document.getElementById("next").addEventListener("click", function(event) {
            event.preventDefault()
          });
        }
        {% endif %}
        {% if student %}
        if ({{pageCount}} >= maxPages) {
          document.getElementById("student_next").addEventListener("click", function(event) {
            event.preventDefault()
          });
        }
        {% endif %}
      }
    </script>

    <script>
//      document.getElementById("demo").innerHTML = maxPages; 
    </script>


</body>

</html>